/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package psis.View;

import javafx.beans.property.ReadOnlyBooleanProperty;
import javafx.beans.property.ReadOnlyDoubleProperty;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.property.ReadOnlyStringProperty;
import javafx.concurrent.Worker;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import psis.Controller.DBcontrol;
import psis.Controller.SendEmail;
import psis.Controller.UserController;
import psis.Model.Patron;


public class LoginView extends javax.swing.JFrame {

    DBcontrol db;
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the PatronDashboard Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        pwd_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Username/ID:");

        jLabel2.setText("Password:");

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_clear.setText("Reset");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Register New Patron");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("Role:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Patron", "Employee", "Admin" }));

        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Check-in");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwd_password)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_login)
                        .addGap(14, 14, 14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwd_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login)
                    .addComponent(btn_clear))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        this.txt_username.setText("");
        this.pwd_password.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String user_name = this.txt_username.getText();
        String password = this.pwd_password.getText();
        Patron user = new Patron("","","",user_name, "", password, "","",null,null,"","");
        UserController login = new UserController(this.db);
        
        String domain = jComboBox1.getSelectedItem().toString();

        if(domain.equals("Patron")){
            if(user_name.length() < 6 || user_name.length() > 6 ){
                JOptionPane.showMessageDialog(rootPane, "Enter Patron ID exactly 6 characters long.", "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else if(password.length() < 7 || password.length() > 15 ){
                JOptionPane.showMessageDialog(rootPane, "Enter password with 7 -15 characters long.", "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Patron role = login.patronlogin(user);
            if(role.getAccess().equals("error")){
                JOptionPane.showMessageDialog(rootPane, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
                this.btn_clearActionPerformed(evt);
            } 
            else if(role.getAccess().equals("denied")){
                JOptionPane.showMessageDialog(rootPane, "Your Access is Denied For Some Reason.", "Login Error", JOptionPane.ERROR_MESSAGE);
                this.btn_clearActionPerformed(evt);
            }
            else{
                
                SwingWorker worker = new SwingWorker<Void, Void>() {
                    @Override
                    public Void doInBackground() {
                        SendEmail.send(role.getEmail(), "New Login", "You have been successfully logged in to iClimbing system.");
                        return null;
                    }
                    @Override
                    public void done() {
                        
                    }
                };
                worker.execute();
                
                if(role.getWalvor().equals("Not Done")){
                    this.dispose();
                    this.setVisible(false);
                    WalverView form = new WalverView();
                    form.main(this.db,role);
                }
                else{
                    this.dispose();
                    this.setVisible(false);
                    PatronDashboard form = new PatronDashboard();
                    form.main(this.db,role);
                }
            }
        }
        else if(domain.equals("Employee")){
            if(password.length() < 7 || password.length() > 15 ){
                JOptionPane.showMessageDialog(rootPane, "Enter password with 7 -15 characters long.", "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String role = login.employeelogin(user);
            if(role.equals("error")){
                JOptionPane.showMessageDialog(rootPane, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
                this.btn_clearActionPerformed(evt);
            } 
            else if(role.equals("denied")){
                JOptionPane.showMessageDialog(rootPane, "Your Access is Denied For Some Reason.", "Login Error", JOptionPane.ERROR_MESSAGE);
                this.btn_clearActionPerformed(evt);
            }
            else{
                this.dispose();
                this.setVisible(false);
                EmployeeDashboard form = new EmployeeDashboard();
                form.main(this.db, role);
            }
        }
        else if(domain.equals("Admin")){
            if(password.length() < 7 || password.length() > 15 ){
                JOptionPane.showMessageDialog(rootPane, "Enter password with 7 -15 characters long.", "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String role = login.adminlogin(user);
            if(role.equals("error")){
                JOptionPane.showMessageDialog(rootPane, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
                this.btn_clearActionPerformed(evt);
            } 
            else if(role.equals("denied")){
                JOptionPane.showMessageDialog(rootPane, "Your Access is Denied For Some Reason.", "Login Error", JOptionPane.ERROR_MESSAGE);
                this.btn_clearActionPerformed(evt);
            }
            else{
                this.dispose();
                this.setVisible(false);
                AdminDashboard form = new AdminDashboard();
                form.main(this.db, role);
            }
        }
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
        RegisterView register = new RegisterView();
        RegisterView.from = "login";
        register.main(db);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
        CheckinView checkin = new CheckinView();
        checkin.main(db);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(final DBcontrol database) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginView form = new LoginView();
                form.db = database;
                form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                form.pack();
                form.setLocationRelativeTo(null);   //  Shows PatronDashboard in the center of the screen
                form.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pwd_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
